name: Publish to NPM
on:
  push:
    branches:
      - "main"
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          always-auth: true

      - name: Install Dependencies
        run: npm install

      - name: Publish to NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --verbose